// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
use diesel::Queryable;
#[derive(Queryable, Debug)]
pub struct Credential {
    pub id: i32,
    pub encrypted_creds: String,
    pub created_at: NaiveDateTime,
    pub user_id: i32,
}

#[derive(Queryable, Debug)]
pub struct Device {
    pub id: i32,
    pub device_id_hash: String,
    pub created_at: NaiveDateTime,
    pub user_id: i32,
}

#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub auth_pub_key: String,
}

